version: 1
disable_existing_loggers: False
formatters:
    simple:
        class: logging.Formatter
        format: "[%(asctime)s] %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    complex:
        format: "[%(asctime)s] %(funcName)s(:%(lineno)d) in %(filename)s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

    main_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/main.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: complex
        filename: logs/error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    main:
        level: INFO
        handlers: [console, main_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, main_file_handler, error_file_handler]